services:
  - type: web
    name: traveltales
    env: php
    plan: free
    buildCommand: ""
    startCommand: ""
    autoDeploy: true
    disk:
      name: uploads
      mountPath: /opt/render/project/src/uploads
      sizeGB: 1